---
name: Ansible Lint
on: # yamllint disable-line rule:truthy
  - pull_request
  - push

jobs:
  lint-ansible:
    name: Lint Ansible role
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for GitHub token to determine reporter type
        run: |
          if [ "${{ github.event_name }}" != "pull_request" ]; then
              echo "REVIEWDOG_REPORTER=local" >> $GITHUB_ENV
          else
              echo "REVIEWDOG_REPORTER=github-pr-review" >> $GITHUB_ENV
          fi

      - name: Run ansible-lint
        uses: reviewdog/action-ansiblelint@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: info
          reporter: ${{ env.REVIEWDOG_REPORTER }}
          ansiblelint_flags: "."

  lint-yaml:
    name: Lint YAML
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for GitHub token to determine reporter type
        run: |
          if [ "${{ github.event_name }}" != "pull_request" ]; then
              echo "REVIEWDOG_REPORTER=local" >> $GITHUB_ENV
          else
              echo "REVIEWDOG_REPORTER=github-pr-review" >> $GITHUB_ENV
          fi

      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: info
          reporter: ${{ env.REVIEWDOG_REPORTER }}
          yamllint_flags: "."

  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for GitHub token to determine reporter type
        run: |
          if [ "${{ github.event_name }}" != "pull_request" ]; then
              echo "REVIEWDOG_REPORTER=local" >> $GITHUB_ENV
          else
              echo "REVIEWDOG_REPORTER=github-pr-review" >> $GITHUB_ENV
          fi

      - name: Run markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: info
          reporter: ${{ env.REVIEWDOG_REPORTER }}
          markdownlint_flags: "."
